# Generated by Django 5.0.14 on 2025-07-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URL',
            new_name='UrlModel',
        ),
    ]
