# Generated by Django 5.0.14 on 2025-07-21 19:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0005_alter_urlmodel_user_alter_urlmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
